### ISSUE TITLE
Swap TimeGrid and Resources

### ISSUE THREAD

**Issue by amanjain-aj** [jquense/react-big-calendar#2278] opened 2022-09-29 07:12 UTC
### Clear and concise description of the problem

 I need to switch the resources view  from header to side panel and the timegrid from the side panel to the top.
 
 In other words, I want the timegrid on the x-axis instead of y-axis

![Screenshot (67)](https://user-images.githubusercontent.com/17477501/192964368-31944d40-7acc-4f2a-8ac0-ccf301cd724d.png)

![Screenshot (68)](https://user-images.githubusercontent.com/17477501/192964394-da01bc16-3167-40e0-a37f-c8c5d9ebd991.png)

### Suggested solution

Currently I don't have any solution for this or how it can be implemented.

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by cutterbl** [comment] 2022-09-29 12:16
This is a duplicate of #1855

**Closed by cutterbl** 2022-09-29 12:16 UTC
Labels: feature request

**Comment by fikaso** [comment] 2023-02-03 14:09
I was wondering if this feature has been implemented. If so, would it be possible to provide some documentation or an example of usage for the same?

I couldn't find any information regarding this feature in the documentation.

Thank you in advance for your time and support.

**Comment by cutterbl** [comment] 2023-02-03 14:34
@fikaso This feature has not been implemented, but is a long standing Feature Request.

**Comment by Shirish759** [comment] 2024-05-29 08:46
has the feature been completed?
